name: job_application
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  analyzer: ^6.2.0
  build_runner: ^2.4.6
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_preview: ^1.1.0
  dio: ^5.3.2
  either_dart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  freezed: ^2.4.2
  get_it: ^7.6.0
  google_fonts: ^5.1.0
  hexcolor: ^3.0.1
  internet_connection_checker: ^1.0.0+1
  json_serializable:
  lottie: ^2.6.0
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.3.1
  pro_shered_preference: ^0.0.7
  retrofit: ^4.0.1
  retrofit_generator: ^7.0.8
  smooth_page_indicator: ^1.1.0
  

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/get_start/
    - assets/logo/
    - assets/onboarding/
    - assets/svg/
    - assets/json/
    - assets/login/
    - assets/iconsSvg/
